### ISSUE TITLE
payload : some images are listed without an extension

### ISSUE THREAD

**Issue by RobbWatershed** [ixilia/hina#12]
e.g. https://api.ixil.cc/hina/payload?id=UmeVc8

Images appear as `https://hina.ixil.cc/rylskyart.com/3119/00`, `https://hina.ixil.cc/rylskyart.com/3119/01`...

They actual URL is `https://hina.ixil.cc/rylskyart.com/3119/00.jpg`, `https://hina.ixil.cc/rylskyart.com/3119/01.jpg`...

**Comment by assintates** [comment]
Issue has been resolved on the new patch.

Issue: 
       Regex Grouping values
