### ISSUE TITLE
Weird thumb URLs

### ISSUE THREAD

**Issue by RobbWatershed** [ixilia/hina#20]
When using the pagination endpoint, I sometimes get weird URLs for jjgirls

e.g. `https://jjgirlsc.ixil.cchttps://pics.jjgirls.com/pictures/adulttime/lina-love/greatest-double-penetration-my18teens/hd-lina-love-11.jpg`
`https://jjgirlsc.ixil.cchttps://pics.jjgirls.com/pictures/sexandsubmission/jada-stevens-mark-davis-mr-pete/sey-undressing-fotossex/hd-jada-stevens-mark-davis-mr-pete-12.jpg`
`https://jjgirlsc.ixil.cchttps://pics.jjgirls.com/pictures/cutiesgalore/viktoria/highsex-amateur-deskbabes/hd-viktoria-9.jpg`
`https://jjgirlsc.ixil.cchttps://pics.jjgirls.com/pictures/outofthefamily/evelin-stone-rion-king/indiansexlounge-brunette-boons-nude/hd-evelin-stone-rion-king-7.jpg`

**Comment by assintates** [comment]
Fixed in New deployment,   All previous Data is waiting to be re-indexed.

**Comment by RobbWatershed** [comment]
All reported URLs have been fixed. Thanks~
