### ISSUE TITLE
Thumbs not loading

### ISSUE THREAD

**Issue by RobbWatershed** [ixilia/hina#35]
When using the thumbs endpoint, I only get 404's

e.g. https://api.ixil.cc/bloom/strat/thumbs/LAlvpx/1
https://api.ixil.cc/bloom/strat/thumbs/ENGmVK/1

**Comment by assintates** [comment]
the endpoint has been moved to 

https://api.ixil.cc/strat/

**Comment by RobbWatershed** [comment]
Fix confirmed, thanks !!
