### ISSUE TITLE
Search with results count but no data

### ISSUE THREAD

**Issue by RobbWatershed** [ixilia/hina#36]
Searching for http://api.ixil.cc/bloom/hina/search?page=1&op=50&query=%22jada%20stevens%22%20%22mark%22

Gives 
```
{
  "data": [],
  "maxres": 1,
  "maxctr": 7
}
```

How come Hina reports 7 results in `maxctr`, but no `data` ? This query worked before the migration...

Same for http://api.ixil.cc/bloom/hina/search?page=1&op=50&query=%22jada%20stevens%22%20%22remy%20lacroix%22 (`maxctr` = 20 / no data), which is a subset of http://api.ixil.cc/bloom/hina/search?page=1&op=50&query=%22jada%20stevens%22%20 (572 results)

Same for http://api.ixil.cc/bloom/hina/search?page=1&op=50&query=%22asian%22%20%22anal%22%20%22glasses%22 (`maxctr` = 15, no data)

**Comment by assintates** [comment]
Deployed #153775f  with fixes.

**Comment by RobbWatershed** [comment]
Confirmed. Thanks
