### ISSUE TITLE
comhttps

### ISSUE THREAD

**Issue by sinsa2** [ixilia/hina#66]
im nub but correct this (source:jiggirl)
https://api.ixil.cc/bloom/hina?source=jjgirls.com&op=1&page=1

thumb: "https://pics.jjgirls.comhttps://pics.jjgirls.com/pictures/trickyspa/zoe-bloom-eric-masterson/scan-brunette-amourgirlz-com/hd-zoe-bloom-eric-masterson-9.jpg"

			var salah = item.thumb;
			var jmlsalah = salah.length;
			var koreksi = salah.substring(24, jmlsalah);
			var cari = salah.search('comhttps');
			if (cari > 1) .............................

and now its ok.

thanks for sharing master, im reques asian cute video (sorry)

**Comment by assintates** [comment]
Issue resolved.


Issue type: Indexer 
Issue: Regex Error
